# [Task 5] Home Credit Scorecard Model
Dikerjakan oleh: Aurelia Sukianto

## Latar Belakang Tugas

Home Credit saat ini sedang menggunakan berbagai macam metode statistik dan Machine Learning untuk membuat prediksi skor kredit. Sekarang, kami meminta anda untuk membuka potensi maksimal dari data kami. Dengan melakukannya, kita dapat memastikan pelanggan yang mampu melakukan pelunasan tidak ditolak ketika melakukan pengajuan pinjaman, dan pinjaman datap diberikan dengan principal, maturity, dan repayment calendar yang akan memotivsi pelanggan untuk sukses. Evaluasi akan dilakukan dengan mengecek seberapa dalam pemahaman analisa yang anda kerjakan. Sebagai catatan, anda perlu menggunakan setidaknya 2 model Machine Learning dimana salah satunya adalah Logistic Regression. Setelah itu, buatlah slide presentasi yang mengandung analisa hasil pemodelan secara end-to-end beserta rekomendasi bisnisnya (maksimal 10 halaman)

## Data Collecting

In [1]:
# connect to my google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# create shortcut do datasets folder
!ln -s "/content/drive/MyDrive/PBI Rakamin/home-credit-default-risk" "/datasets"

In [3]:
import pandas as pd

In [4]:
application_train_path = "/datasets/application_train.csv"
df_application_train = pd.read_csv(application_train_path)

In [5]:
df_application_train.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [6]:
application_test_path = "/datasets/application_test.csv"
df_application_test = pd.read_csv(application_test_path)

In [7]:
df_application_test.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100001         Cash loans           F            N               Y   
1      100005         Cash loans           M            N               Y   
2      100013         Cash loans           M            Y               Y   
3      100028         Cash loans           F            N               Y   
4      100038         Cash loans           M            Y               N   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          135000.0    568800.0      20560.5         450000.0   
1             0           99000.0    222768.0      17370.0         180000.0   
2             0          202500.0    663264.0      69777.0         630000.0   
3             2          315000.0   1575000.0      49018.5        1575000.0   
4             1          180000.0    625500.0      32067.0         625500.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        0.0                        0.0   
4                        NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         NaN                        NaN   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         0.0  
1                        0.0                         3.0  
2                        1.0                         4.0  
3                        0.0                         3.0  
4                        NaN                         NaN  

[5 rows x 121 columns]

In [8]:
bureau_balance_path = "/datasets/bureau_balance.csv"
df_bureau_balance = pd.read_csv(bureau_balance_path)

In [9]:
df_bureau_balance.head()

SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [10]:
bureau_path = "/datasets/bureau.csv"
df_bureau = pd.read_csv(bureau_path)

In [11]:
df_bureau.head()

SK_ID_CURR  SK_ID_BUREAU CREDIT_ACTIVE CREDIT_CURRENCY  DAYS_CREDIT  \
0      215354       5714462        Closed      currency 1         -497   
1      215354       5714463        Active      currency 1         -208   
2      215354       5714464        Active      currency 1         -203   
3      215354       5714465        Active      currency 1         -203   
4      215354       5714466        Active      currency 1         -629   

   CREDIT_DAY_OVERDUE  DAYS_CREDIT_ENDDATE  DAYS_ENDDATE_FACT  \
0                   0               -153.0             -153.0   
1                   0               1075.0                NaN   
2                   0                528.0                NaN   
3                   0                  NaN                NaN   
4                   0               1197.0                NaN   

   AMT_CREDIT_MAX_OVERDUE  CNT_CREDIT_PROLONG  AMT_CREDIT_SUM  \
0                     NaN                   0         91323.0   
1                     NaN                   0        225000.0   
2                     NaN                   0        464323.5   
3                     NaN                   0         90000.0   
4                 77674.5                   0       2700000.0   

   AMT_CREDIT_SUM_DEBT  AMT_CREDIT_SUM_LIMIT  AMT_CREDIT_SUM_OVERDUE  \
0                  0.0                   NaN                     0.0   
1             171342.0                   NaN                     0.0   
2                  NaN                   NaN                     0.0   
3                  NaN                   NaN                     0.0   
4                  NaN                   NaN                     0.0   

       CREDIT_TYPE  DAYS_CREDIT_UPDATE  AMT_ANNUITY  
0  Consumer credit                -131          NaN  
1      Credit card                 -20          NaN  
2  Consumer credit                 -16          NaN  
3      Credit card                 -16          NaN  
4  Consumer credit                 -21          NaN

In [12]:
credit_card_balance_path = "/datasets/credit_card_balance.csv"
df_credit_card_balance = pd.read_csv(credit_card_balance_path)

In [13]:
df_credit_card_balance.head()

SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  AMT_BALANCE  \
0     2562384      378907              -6       56.970   
1     2582071      363914              -1    63975.555   
2     1740877      371185              -7    31815.225   
3     1389973      337855              -4   236572.110   
4     1891521      126868              -1   453919.455   

   AMT_CREDIT_LIMIT_ACTUAL  AMT_DRAWINGS_ATM_CURRENT  AMT_DRAWINGS_CURRENT  \
0                   135000                       0.0                 877.5   
1                    45000                    2250.0                2250.0   
2                   450000                       0.0                   0.0   
3                   225000                    2250.0                2250.0   
4                   450000                       0.0               11547.0   

   AMT_DRAWINGS_OTHER_CURRENT  AMT_DRAWINGS_POS_CURRENT  \
0                         0.0                     877.5   
1                         0.0                       0.0   
2                         0.0                       0.0   
3                         0.0                       0.0   
4                         0.0                   11547.0   

   AMT_INST_MIN_REGULARITY  ...  AMT_RECIVABLE  AMT_TOTAL_RECEIVABLE  \
0                 1700.325  ...          0.000                 0.000   
1                 2250.000  ...      64875.555             64875.555   
2                 2250.000  ...      31460.085             31460.085   
3                11795.760  ...     233048.970            233048.970   
4                22924.890  ...     453919.455            453919.455   

   CNT_DRAWINGS_ATM_CURRENT  CNT_DRAWINGS_CURRENT  CNT_DRAWINGS_OTHER_CURRENT  \
0                       0.0                     1                         0.0   
1                       1.0                     1                         0.0   
2                       0.0                     0                         0.0   
3                       1.0                     1                         0.0   
4                       0.0                     1                         0.0   

   CNT_DRAWINGS_POS_CURRENT  CNT_INSTALMENT_MATURE_CUM  NAME_CONTRACT_STATUS  \
0                       1.0                       35.0                Active   
1                       0.0                       69.0                Active   
2                       0.0                       30.0                Active   
3                       0.0                       10.0                Active   
4                       1.0                      101.0                Active   

   SK_DPD  SK_DPD_DEF  
0       0           0  
1       0           0  
2       0           0  
3       0           0  
4       0           0  

[5 rows x 23 columns]

In [14]:
installments_payments_path = "/datasets/installments_payments.csv"
df_installments_payments = pd.read_csv(installments_payments_path)

In [15]:
df_installments_payments.head()

SK_ID_PREV  SK_ID_CURR  NUM_INSTALMENT_VERSION  NUM_INSTALMENT_NUMBER  \
0     1054186      161674                     1.0                      6   
1     1330831      151639                     0.0                     34   
2     2085231      193053                     2.0                      1   
3     2452527      199697                     1.0                      3   
4     2714724      167756                     1.0                      2   

   DAYS_INSTALMENT  DAYS_ENTRY_PAYMENT  AMT_INSTALMENT  AMT_PAYMENT  
0          -1180.0             -1187.0        6948.360     6948.360  
1          -2156.0             -2156.0        1716.525     1716.525  
2            -63.0               -63.0       25425.000    25425.000  
3          -2418.0             -2426.0       24350.130    24350.130  
4          -1383.0             -1366.0        2165.040     2160.585

In [16]:
POS_CASH_balance_path = "/datasets/POS_CASH_balance.csv"
df_POS_CASH_balance = pd.read_csv(POS_CASH_balance_path)

In [17]:
df_POS_CASH_balance.head()

SK_ID_PREV  SK_ID_CURR  MONTHS_BALANCE  CNT_INSTALMENT  \
0     1803195      182943             -31            48.0   
1     1715348      367990             -33            36.0   
2     1784872      397406             -32            12.0   
3     1903291      269225             -35            48.0   
4     2341044      334279             -35            36.0   

   CNT_INSTALMENT_FUTURE NAME_CONTRACT_STATUS  SK_DPD  SK_DPD_DEF  
0                   45.0               Active       0           0  
1                   35.0               Active       0           0  
2                    9.0               Active       0           0  
3                   42.0               Active       0           0  
4                   35.0               Active       0           0

In [18]:
previous_application_path = "/datasets/previous_application.csv"
df_previous_application = pd.read_csv(previous_application_path)

In [19]:
df_previous_application.head()

SK_ID_PREV  SK_ID_CURR NAME_CONTRACT_TYPE  AMT_ANNUITY  AMT_APPLICATION  \
0     2030495      271877     Consumer loans     1730.430          17145.0   
1     2802425      108129         Cash loans    25188.615         607500.0   
2     2523466      122040         Cash loans    15060.735         112500.0   
3     2819243      176158         Cash loans    47041.335         450000.0   
4     1784265      202054         Cash loans    31924.395         337500.0   

   AMT_CREDIT  AMT_DOWN_PAYMENT  AMT_GOODS_PRICE WEEKDAY_APPR_PROCESS_START  \
0     17145.0               0.0          17145.0                   SATURDAY   
1    679671.0               NaN         607500.0                   THURSDAY   
2    136444.5               NaN         112500.0                    TUESDAY   
3    470790.0               NaN         450000.0                     MONDAY   
4    404055.0               NaN         337500.0                   THURSDAY   

   HOUR_APPR_PROCESS_START  ... NAME_SELLER_INDUSTRY  CNT_PAYMENT  \
0                       15  ...         Connectivity         12.0   
1                       11  ...                  XNA         36.0   
2                       11  ...                  XNA         12.0   
3                        7  ...                  XNA         12.0   
4                        9  ...                  XNA         24.0   

   NAME_YIELD_GROUP       PRODUCT_COMBINATION  DAYS_FIRST_DRAWING  \
0            middle  POS mobile with interest            365243.0   
1        low_action          Cash X-Sell: low            365243.0   
2              high         Cash X-Sell: high            365243.0   
3            middle       Cash X-Sell: middle            365243.0   
4              high         Cash Street: high                 NaN   

  DAYS_FIRST_DUE DAYS_LAST_DUE_1ST_VERSION  DAYS_LAST_DUE DAYS_TERMINATION  \
0          -42.0                     300.0          -42.0            -37.0   
1         -134.0                     916.0       365243.0         365243.0   
2         -271.0                      59.0       365243.0         365243.0   
3         -482.0                    -152.0         -182.0           -177.0   
4            NaN                       NaN            NaN              NaN   

  NFLAG_INSURED_ON_APPROVAL  
0                       0.0  
1                       1.0  
2                       1.0  
3                       1.0  
4                       NaN  

[5 rows x 37 columns]

In [20]:
sample_submission_path = "/datasets/sample_submission.csv"
df_sample_submission = pd.read_csv(sample_submission_path)

In [21]:
df_sample_submission.head()

SK_ID_CURR  TARGET
0      100001     0.5
1      100005     0.5
2      100013     0.5
3      100028     0.5
4      100038     0.5

## Data Visualization

In [22]:
# Menggabungkan dua dataset application_test dan application_train menggunakan metode concat
application = pd.concat([df_application_train, df_application_test], ignore_index=True)

# Menyimpan hasil penggabungan ke dalam file CSV
application.to_csv('application.csv', index=False)

df_application = pd.read_csv('application.csv')

In [23]:
df_application.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002     1.0         Cash loans           M            N   
1      100003     0.0         Cash loans           F            N   
2      100004     0.0    Revolving loans           M            Y   
3      100006     0.0         Cash loans           F            N   
4      100007     0.0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_0, *['SK_ID_CURR'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_1, *['TARGET'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_2, *['AMT_INCOME_TOTAL'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_3, *['AMT_CREDIT'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_4, *['SK_ID_CURR'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_5, *['TARGET'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_6, *['AMT_INCOME_TOTAL'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_7, *['AMT_CREDIT'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_8, *['NAME_CONTRACT_TYPE'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_9, *['CODE_GENDER'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_10, *['FLAG_OWN_CAR'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_11, *['FLAG_OWN_REALTY'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(_df_12, *[[['SK_ID_CURR', 'TARGET'], ['TARGET', 'AMT_INCOME_TOTAL'], ['AMT_INCOME_TOTAL', 'AMT_CREDIT'], ['AMT_CREDIT', 'AMT_ANNUITY']]], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_13, *['NAME_CONTRACT_TYPE', 'CODE_GENDER'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_14, *['CODE_GENDER', 'FLAG_OWN_CAR'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_15, *['FLAG_OWN_CAR', 'FLAG_OWN_REALTY'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_16, *['FLAG_OWN_REALTY', 'NAME_TYPE_SUITE'], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_17, *['SK_ID_CURR', 'NAME_CONTRACT_TYPE'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_18, *['SK_ID_CURR', 'CODE_GENDER'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_19, *['SK_ID_CURR', 'FLAG_OWN_CAR'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_20, *['SK_ID_CURR', 'FLAG_OWN_REALTY'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_21, *['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_22, *['SK_ID_CURR', 'TARGET', 'CODE_GENDER'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_23, *['SK_ID_CURR', 'TARGET', 'FLAG_OWN_CAR'], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(_df_24, *['SK_ID_CURR', 'TARGET', 'FLAG_OWN_REALTY'], **{})
chart

## Data Cleaning

### application_train.csv

In [24]:
# Menghapus baris dengan nilai null/NaN
application_train_cleaned = df_application_train.dropna()

# Menghapus baris duplikat
application_train_cleaned = application_train_cleaned.drop_duplicates()

# Menyimpan dataset yang telah dibersihkan
application_train_cleaned.to_csv('application_train_cleaned.csv', index=False)

df_application_train_cleaned = pd.read_csv('application_train_cleaned.csv')
df_application_train_cleaned.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100083       0         Cash loans           M            Y   
1      100145       0         Cash loans           F            Y   
2      100179       0         Cash loans           F            Y   
3      100190       0         Cash loans           M            Y   
4      100295       1         Cash loans           M            Y   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          103500.0    573628.5      24435.0   
1               Y             1          202500.0    260725.5      16789.5   
2               N             0          202500.0    675000.0      53329.5   
3               N             0          162000.0    263686.5      24781.5   
4               N             1          225000.0   1019205.0      31032.0   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 1                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        1.0   
3                         0.0                        0.0   
4                         0.0                        6.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         3.0  
1                        0.0                         3.0  
2                        0.0                         4.0  
3                        0.0                         3.0  
4                        0.0                         1.0  

[5 rows x 122 columns]

### application_test.csv

In [25]:
# Menghapus baris dengan nilai null/NaN
application_test_cleaned = df_application_test.dropna()

# Menghapus baris duplikat
application_test_cleaned = application_test_cleaned.drop_duplicates()

# Menyimpan dataset yang telah dibersihkan
application_test_cleaned.to_csv('application_test_cleaned.csv', index=False)

df_application_test_cleaned = pd.read_csv('application_test_cleaned.csv')
df_application_test_cleaned.head()

SK_ID_CURR NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
0      100107         Cash loans           M            Y               Y   
1      100128         Cash loans           F            Y               Y   
2      100561         Cash loans           M            Y               Y   
3      100699         Cash loans           M            Y               Y   
4      100770         Cash loans           M            Y               N   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          180000.0    296280.0      21690.0         225000.0   
1             1          225000.0    431280.0      23526.0         360000.0   
2             0          180000.0     67500.0       8140.5          67500.0   
3             1          225000.0    323460.0      23134.5         270000.0   
4             0          202500.0    697500.0      33687.0         697500.0   

   ... FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                0                0                0                0   
1  ...                0                0                0                0   
2  ...                0                0                0                0   
3  ...                0                0                0                0   
4  ...                0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        0.0                        0.0   
4                        0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        1.0                         3.0  
1                        3.0                         4.0  
2                        0.0                         2.0  
3                        0.0                         3.0  
4                        0.0                         0.0  

[5 rows x 121 columns]

## Data Processing

### application_train.csv

In [26]:
# Melihat tipe data dan informasi kolom
print(df_application_train_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8602 entries, 0 to 8601
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 8.0+ MB
None


In [27]:
# Melihat statistik deskriptif dataset
print(df_application_train_cleaned.describe())

          SK_ID_CURR       TARGET  CNT_CHILDREN  AMT_INCOME_TOTAL  \
count    8602.000000  8602.000000   8602.000000      8.602000e+03   
mean   279002.948617     0.061149      0.602534      2.228724e+05   
std    103218.951947     0.239617      0.775007      1.414204e+05   
min    100083.000000     0.000000      0.000000      3.375000e+04   
25%    188965.750000     0.000000      0.000000      1.350000e+05   
50%    278239.000000     0.000000      0.000000      1.935000e+05   
75%    370083.500000     0.000000      1.000000      2.700000e+05   
max    456226.000000     1.000000      5.000000      4.500000e+06   

         AMT_CREDIT    AMT_ANNUITY  AMT_GOODS_PRICE  \
count  8.602000e+03    8602.000000     8.602000e+03   
mean   6.999987e+05   31558.948326     6.338337e+05   
std    4.649119e+05   16587.353415     4.294083e+05   
min    4.500000e+04    2317.500000     4.500000e+04   
25%    3.150000e+05   19548.000000     2.700000e+05   
50%    5.850000e+05   29209.500000     4.950000e

In [28]:
df_application_train_cleaned['NAME_CONTRACT_TYPE'] = df_application_train_cleaned['NAME_CONTRACT_TYPE'].replace(['Cash loans', 'Revolving loans'], [0, 1])
df_application_train_cleaned['NAME_CONTRACT_TYPE'].unique()

array([0, 1])

In [66]:
# Menghitung frekuensi kemunculan setiap nilai di Kolom1
value_counts = df_application_train_cleaned['NAME_CONTRACT_TYPE'].value_counts()

# Menghitung persentase relatif kemunculan setiap nilai
percentage = (value_counts / len(df_application_train_cleaned)) * 100

# Hasilnya:
print("Frekuensi kemunculan setiap nilai:")
print(value_counts)

print("\nPersentase relatif kemunculan setiap nilai:")
print(percentage)

Frekuensi kemunculan setiap nilai:
0    7660
1     942
Name: NAME_CONTRACT_TYPE, dtype: int64

Persentase relatif kemunculan setiap nilai:
0    89.049058
1    10.950942
Name: NAME_CONTRACT_TYPE, dtype: float64


In [29]:
df_application_train_cleaned['CODE_GENDER'] = df_application_train_cleaned['CODE_GENDER'].replace(['M', 'F'], [0, 1])
df_application_train_cleaned['CODE_GENDER'].unique()

array([0, 1])

In [30]:
df_application_train_cleaned['FLAG_OWN_CAR'] = df_application_train_cleaned['FLAG_OWN_CAR'].replace(['N', 'Y'], [0, 1])
df_application_train_cleaned['FLAG_OWN_CAR'].unique()

array([1])

In [31]:
df_application_train_cleaned['FLAG_OWN_REALTY'] = df_application_train_cleaned['FLAG_OWN_REALTY'].replace(['N', 'Y'], [0, 1])
df_application_train_cleaned['FLAG_OWN_REALTY'].unique()

array([1, 0])

In [32]:
df_application_train_cleaned['NAME_TYPE_SUITE'].unique()

array(['Unaccompanied', 'Family', 'Spouse, partner', 'Children',
       'Other_A', 'Other_B', 'Group of people'], dtype=object)

In [33]:
df_application_train_cleaned['NAME_TYPE_SUITE'] = df_application_train_cleaned['NAME_TYPE_SUITE'].replace(['Unaccompanied', 'Family', 'Spouse, partner', 'Children',
       'Other_A', 'Other_B', 'Group of people'], [0, 1, 2, 3, 4, 5, 6])
df_application_train_cleaned['NAME_TYPE_SUITE'].unique()

array([0, 1, 2, 3, 4, 5, 6])

In [34]:
df_application_train_cleaned['NAME_INCOME_TYPE'].unique()

array(['Working', 'Commercial associate', 'State servant'], dtype=object)

In [35]:
df_application_train_cleaned['NAME_INCOME_TYPE'] = df_application_train_cleaned['NAME_INCOME_TYPE'].replace(['Working', 'Commercial associate', 'State servant'], [0, 1, 2])
df_application_train_cleaned['NAME_INCOME_TYPE'].unique()

array([0, 1, 2])

In [36]:
df_application_train_cleaned['NAME_EDUCATION_TYPE'].unique()

array(['Secondary / secondary special', 'Higher education',
       'Incomplete higher', 'Lower secondary', 'Academic degree'],
      dtype=object)

In [37]:
df_application_train_cleaned['NAME_EDUCATION_TYPE'] = df_application_train_cleaned['NAME_EDUCATION_TYPE'].replace(['Secondary / secondary special', 'Higher education',
       'Incomplete higher', 'Lower secondary', 'Academic degree'], [0, 1, 2, 3, 4])
df_application_train_cleaned['NAME_EDUCATION_TYPE'].unique()

array([0, 1, 2, 3, 4])

In [38]:
df_application_train_cleaned['NAME_FAMILY_STATUS'].unique()

array(['Married', 'Separated', 'Single / not married', 'Widow',
       'Civil marriage'], dtype=object)

In [39]:
df_application_train_cleaned['NAME_FAMILY_STATUS'] = df_application_train_cleaned['NAME_FAMILY_STATUS'].replace(['Married', 'Separated', 'Single / not married', 'Widow',
       'Civil marriage'], [0, 1, 2, 3, 4])
df_application_train_cleaned['NAME_FAMILY_STATUS'].unique()

array([0, 1, 2, 3, 4])

In [40]:
df_application_train_cleaned['NAME_HOUSING_TYPE'].unique()

array(['House / apartment', 'With parents', 'Municipal apartment',
       'Office apartment', 'Co-op apartment', 'Rented apartment'],
      dtype=object)

In [41]:
df_application_train_cleaned['NAME_HOUSING_TYPE'] = df_application_train_cleaned['NAME_HOUSING_TYPE'].replace(['House / apartment', 'With parents', 'Municipal apartment',
       'Office apartment', 'Co-op apartment', 'Rented apartment'], [0, 1, 2, 3, 4, 5])
df_application_train_cleaned['NAME_HOUSING_TYPE'].unique()

array([0, 1, 2, 3, 4, 5])

In [42]:
kolom_string = df_application_train_cleaned.select_dtypes(include=['object'])

# Mengubah nilai-nilai string menjadi numerik menggunakan Label Encoding
df_application_train_cleaned[kolom_string.columns] = kolom_string.apply(lambda x: pd.factorize(x)[0])

In [43]:
df_application_train_cleaned.head()

SK_ID_CURR  TARGET  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  \
0      100083       0                   0            0             1   
1      100145       0                   0            1             1   
2      100179       0                   0            1             1   
3      100190       0                   0            0             1   
4      100295       1                   0            0             1   

   FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                1             0          103500.0    573628.5      24435.0   
1                1             1          202500.0    260725.5      16789.5   
2                0             0          202500.0    675000.0      53329.5   
3                0             0          162000.0    263686.5      24781.5   
4                0             1          225000.0   1019205.0      31032.0   

   ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  \
0  ...                 0                 0                 0   
1  ...                 0                 0                 0   
2  ...                 0                 0                 0   
3  ...                 0                 0                 0   
4  ...                 1                 0                 0   

   FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                 0                         0.0                        0.0   
1                 0                         0.0                        0.0   
2                 0                         0.0                        0.0   
3                 0                         0.0                        0.0   
4                 0                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        1.0   
3                         0.0                        0.0   
4                         0.0                        6.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         3.0  
1                        0.0                         3.0  
2                        0.0                         4.0  
3                        0.0                         3.0  
4                        0.0                         1.0  

[5 rows x 122 columns]

### application_test.csv

In [44]:
# Melihat tipe data dan informasi kolom
print(df_application_test_cleaned.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1739 entries, 0 to 1738
Columns: 121 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(40), object(16)
memory usage: 1.6+ MB
None


In [45]:
# Melihat statistik deskriptif dataset
print(df_application_test_cleaned.describe())

          SK_ID_CURR  CNT_CHILDREN  AMT_INCOME_TOTAL    AMT_CREDIT  \
count    1739.000000   1739.000000      1.739000e+03  1.739000e+03   
mean   275115.886717      0.612996      2.339756e+05  6.644330e+05   
std    104424.592035      0.784834      1.246777e+05  4.704811e+05   
min    100107.000000      0.000000      5.400000e+04  4.500000e+04   
25%    184244.000000      0.000000      1.575000e+05  3.014640e+05   
50%    271806.000000      0.000000      2.025000e+05  5.391000e+05   
75%    364425.000000      1.000000      2.700000e+05  8.955000e+05   
max    455959.000000      4.000000      1.350000e+06  2.156400e+06   

         AMT_ANNUITY  AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  \
count    1739.000000     1.739000e+03                 1739.000000   
mean    35229.431282     6.037845e+05                    0.024186   
std     19180.893448     4.397274e+05                    0.016875   
min      2295.000000     4.500000e+04                    0.001276   
25%     21798.000000    

In [46]:
df_application_test_cleaned['NAME_CONTRACT_TYPE'] = df_application_test_cleaned['NAME_CONTRACT_TYPE'].replace(['Cash loans', 'Revolving loans'], [0, 1])
df_application_test_cleaned['NAME_CONTRACT_TYPE'].unique()

array([0, 1])

In [47]:
df_application_test_cleaned['CODE_GENDER'] = df_application_test_cleaned['CODE_GENDER'].replace(['M', 'F'], [0, 1])
df_application_test_cleaned['CODE_GENDER'].unique()

array([0, 1])

In [48]:
df_application_test_cleaned['FLAG_OWN_CAR'] = df_application_test_cleaned['FLAG_OWN_CAR'].replace(['N', 'Y'], [0, 1])
df_application_test_cleaned['FLAG_OWN_CAR'].unique()

array([1])

In [49]:
df_application_test_cleaned['FLAG_OWN_REALTY'] = df_application_test_cleaned['FLAG_OWN_REALTY'].replace(['N', 'Y'], [0, 1])
df_application_test_cleaned['FLAG_OWN_REALTY'].unique()

array([1, 0])

In [50]:
df_application_test_cleaned['NAME_TYPE_SUITE'] = df_application_test_cleaned['NAME_TYPE_SUITE'].replace(['Unaccompanied', 'Family', 'Spouse, partner', 'Children',
       'Other_A', 'Other_B', 'Group of people'], [0, 1, 2, 3, 4, 5, 6])
df_application_test_cleaned['NAME_TYPE_SUITE'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [51]:
df_application_test_cleaned['NAME_INCOME_TYPE'] = df_application_test_cleaned['NAME_INCOME_TYPE'].replace(['Working', 'Commercial associate', 'State servant'], [0, 1, 2])
df_application_test_cleaned['NAME_INCOME_TYPE'].unique()

array([0, 1, 2])

In [52]:
df_application_test_cleaned['NAME_EDUCATION_TYPE'] = df_application_test_cleaned['NAME_EDUCATION_TYPE'].replace(['Secondary / secondary special', 'Higher education',
       'Incomplete higher', 'Lower secondary', 'Academic degree'], [0, 1, 2, 3, 4])
df_application_test_cleaned['NAME_EDUCATION_TYPE'].unique()

array([0, 1, 2, 4, 3])

In [53]:
df_application_test_cleaned['NAME_FAMILY_STATUS'] = df_application_test_cleaned['NAME_FAMILY_STATUS'].replace(['Married', 'Separated', 'Single / not married', 'Widow',
       'Civil marriage'], [0, 1, 2, 3, 4])
df_application_test_cleaned['NAME_FAMILY_STATUS'].unique()

array([4, 0, 2, 3, 1])

In [54]:
df_application_test_cleaned['NAME_HOUSING_TYPE'] = df_application_test_cleaned['NAME_HOUSING_TYPE'].replace(['House / apartment', 'With parents', 'Municipal apartment',
       'Office apartment', 'Co-op apartment', 'Rented apartment'], [0, 1, 2, 3, 4, 5])
df_application_test_cleaned['NAME_HOUSING_TYPE'].unique()

array([0, 1, 2, 3, 4, 5])

In [55]:
kolom_test_string = df_application_test_cleaned.select_dtypes(include=['object'])

# Mengubah nilai-nilai string menjadi numerik menggunakan Label Encoding
df_application_test_cleaned[kolom_string.columns] = kolom_test_string.apply(lambda x: pd.factorize(x)[0])

In [56]:
df_application_test_cleaned.head()

SK_ID_CURR  NAME_CONTRACT_TYPE  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0      100107                   0            0             1                1   
1      100128                   0            1             1                1   
2      100561                   0            0             1                1   
3      100699                   0            0             1                1   
4      100770                   0            0             1                0   

   CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
0             0          180000.0    296280.0      21690.0         225000.0   
1             1          225000.0    431280.0      23526.0         360000.0   
2             0          180000.0     67500.0       8140.5          67500.0   
3             1          225000.0    323460.0      23134.5         270000.0   
4             0          202500.0    697500.0      33687.0         697500.0   

   ...  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  \
0  ...                 0                 0                 0   
1  ...                 0                 0                 0   
2  ...                 0                 0                 0   
3  ...                 0                 0                 0   
4  ...                 0                 0                 0   

   FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
0                 0                         0.0                        0.0   
1                 0                         0.0                        0.0   
2                 0                         0.0                        0.0   
3                 0                         0.0                        0.0   
4                 0                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         0.0                        0.0   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        1.0                         3.0  
1                        3.0                         4.0  
2                        0.0                         2.0  
3                        0.0                         3.0  
4                        0.0                         0.0  

[5 rows x 121 columns]

## Modelling

In [60]:
# Membagi dataset menjadi data latih dan data uji

from sklearn.model_selection import train_test_split

X = df_application_train_cleaned
y = df_application_train_cleaned['TARGET']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

### With Logistic Regression

In [64]:
# Impor pustaka yang diperlukan
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Membuat model Logistic Regression
lr_model = LogisticRegression()

# Melatih model dengan data latih
lr_model.fit(X_train, y_train)

# Memprediksi kelas data uji
lr_y_pred = lr_model.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, lr_y_pred)
print(f'Akurasi: {accuracy:.2f}')

# Menampilkan metrik evaluasi lainnya
print(classification_report(y_test, lr_y_pred))

# Menampilkan matriks konfusi
lr_conf_matrix = confusion_matrix(y_test, lr_y_pred)
print('Matriks Konfusi:')
print(lr_conf_matrix)


Akurasi: 0.94
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      2425
           1       0.00      0.00      0.00       156

    accuracy                           0.94      2581
   macro avg       0.47      0.50      0.48      2581
weighted avg       0.88      0.94      0.91      2581

Matriks Konfusi:
[[2425    0]
 [ 156    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### With Naive Bayes

In [65]:
# Impor pustaka yang diperlukan
from sklearn.naive_bayes import GaussianNB

# Membuat model Naive Bayes (Gaussian Naive Bayes)
nb_model = GaussianNB()

# Melatih model dengan data latih
nb_model.fit(X_train, y_train)

# Memprediksi kelas data uji
nb_y_pred = nb_model.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, nb_y_pred)
print(f'Akurasi: {accuracy:.2f}')

# Menampilkan metrik evaluasi lainnya
print(classification_report(y_test, nb_y_pred))

# Menampilkan matriks konfusi
nb_conf_matrix = confusion_matrix(y_test, nb_y_pred)
print('Matriks Konfusi:')
print(nb_conf_matrix)


Akurasi: 0.94
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      2425
           1       0.00      0.00      0.00       156

    accuracy                           0.94      2581
   macro avg       0.47      0.50      0.48      2581
weighted avg       0.88      0.94      0.91      2581

Matriks Konfusi:
[[2425    0]
 [ 156    0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
